### ISSUE TITLE
Question about support for recent versions of Elasticsearch 

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#431]
What is the most recent version of Elasticsearch supported by SnowOwl?
Would a 6.5 version work as an example? (that's the one we have at the moment in our cluster so I just want to make sure).

What about the latest stable version? 7.4.x https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html

Thanks!

**Comment by cmark** [comment]
Hi @martinmart92,

The most recent version of Elasticsearch that is supported by Snow Owl is `v6.8.x` (the latest is `v6.8.4` and we will upgrade our dependencies to this version for the upcoming `7.2.0` release).
I think the Elasticsearch v6.8.x HTTP and TCP clients (which are used by Snow Owl internally) should be compatible with a `6.5.0` cluster. 
Feel free to experiment with it and report any problems/issues you get.

About the Elasticsearch 7.x upgrade:
There was a huge architectural change in the Elasticsearch 7.x release, which is mostly supported by Snow Owl (type mapping changes and indexing structure) and it should be possible to migrate the indexes to work in the new format, but there are new search API restrictions introduced in Elasticseach 7.x which are currently not supported by Snow Owl.

We suggest using Elasticsearch 6.x for the moment, but the 7.x upgrade is on our radar as well, probably going to happen in an upcoming release (maybe in `7.3` or in `7.4`).

Let me know if you have any further questions.

Cheers,
Mark

**Comment by martinmart92** [comment]
thank you for your detailed answer :)

**Comment by martinmart92** [comment]
with a ES 6.5, I got the following:

```
[2019-11-18T14:48:02.529] INFO   Container: b42feae7-f784-4130-8f62-5b879c5098c5 index.validations                                                Preparing 'validations' indexes... 
[2019-11-18T14:48:02.863] ERROR  Container: b42feae7-f784-4130-8f62-5b879c5098c5 snowowl                                                          Couldn't check the existence of ES index 'validations-validationissue'. com.b2international.index.IndexException: Couldn't check the existence of ES index 'validations-validationissue'.
	at com.b2international.index.es.admin.EsIndexAdmin.exists(EsIndexAdmin.java:137)
	at com.b2international.index.es.admin.EsIndexAdmin.create(EsIndexAdmin.java:155)
	at com.b2international.snowowl.core.internal.validation.ValidationRepository.<init>(ValidationRepository.java:43)
	at com.b2international.snowowl.core.internal.validation.ValidationPlugin.preRun(ValidationPlugin.java:79)
	at com.b2international.snowowl.core.setup.Plugins.preRun(Plugins.java:88)
	at com.b2international.snowowl.core.SnowOwl.run(SnowOwl.java:286)
	at com.b2international.snowowl.core.SnowOwl.run(SnowOwl.java:267)
	at com.b2international.snowowl.core.SnowOwl.run(SnowOwl.java:255)
	at com.b2international.snowowl.server.product.SnowOwlServerActivator.start(SnowOwlServerActivator.java:51)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:598)
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.elasticsearch.ElasticsearchStatusException: method [HEAD], host [https://vpc-es-snowowl-some-path.eu-west-1.es.amazonaws.com], URI [/validations-validationissue?ignore_throttled=false&include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2027)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1777)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:1109)
	at com.b2international.index.es.client.http.IndicesHttpClient.exists(IndicesHttpClient.java:66)
	at com.b2international.index.es.admin.EsIndexAdmin.exists(EsIndexAdmin.java:135)
	... 26 common frames omitted
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [https://vpc-es-snowowl-some-path.eu-west-1.es.amazonaws.com], URI [/validations-validationissue?ignore_throttled=false&include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:936)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764)
	... 30 common frames omitted
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [https://vpc-es-snowowl-some-path.eu-west-1.es.amazonaws.com], URI [/validations-validationissue?ignore_throttled=false&include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:552)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:537)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.responseReceived(HttpAsyncRequestExecutor.java:315)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:255)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
after some digging I got the impression that ignore_throttled and include_type_name make the following query fail (400)

`curl -I  "https://vpc-es-some-path.eu-west-1.es.amazonaws.com/validations-validationissue?ignore_throttled=false&include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true"`

maybe I should upgrade my elasticsearch version in AWS?

**Comment by cmark** [comment]
Hi @martinmart92,

This could be something that might require an upgrade on your Elasticsearch cluster to `v6.8.2`. The Elasticsearch High-level HTTP Client has been developed during the 6.x releases of Elasticsearch and there could be something that is **not** backward compatible and requires an upgrade. It's probably worth checking their release notes since the 6.5 release.

We will investigate the issue and get back to you.

Cheers,
Mark

**Comment by cmark** [comment]
Hi @martinmart92,

Just to let you know, the process to upgrade to Elasticsearch 7.x (as of today, 7.5.2) has been started. You can track the progress on this branch: 
https://github.com/b2ihealthcare/snow-owl/tree/upgrade/elasticsearch-7.x
And the PR: https://github.com/b2ihealthcare/snow-owl/pull/478

Cheers,
Mark

**Comment by cmark** [comment]
The Elasticsearch 7.5.2 version is now supported by Snow Owl 7.x.
_NOTE: Any data indexed with Elasticsearch 6.8.x can be safely moved to Elasticsearch 7.5.2 without any kind of migration._ 
Feel free to try it out using the latest Docker image. Resolving issue as fixed.
