### ISSUE TITLE
connection to AWS Elasticsearch: `_settings`

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#436]
I got the following error when trying to start Snow-owl `7.x`:

```
[2019-11-19T11:49:15.714] ERROR  Container: a8a4fc02-d3f8-4644-aa62-880362697eb5 snowowl                                                          Couldn't execute bulk updates com.b2international.index.IndexException: Couldn't execute bulk updates
	at com.b2international.index.es.EsDocumentWriter.commit(EsDocumentWriter.java:153)
	at com.b2international.snowowl.datastore.remotejobs.RemoteJobTracker.lambda$0(RemoteJobTracker.java:121)
	at com.b2international.index.DefaultIndex.write(DefaultIndex.java:47)
	at com.b2international.snowowl.datastore.remotejobs.RemoteJobTracker.<init>(RemoteJobTracker.java:111)
	at com.b2international.snowowl.core.repository.RepositoryPlugin.initializeJobSupport(RepositoryPlugin.java:232)
	at com.b2international.snowowl.core.repository.RepositoryPlugin.run(RepositoryPlugin.java:221)
	at com.b2international.snowowl.core.setup.Plugins.run(Plugins.java:74)
	at com.b2international.snowowl.core.SnowOwl.run(SnowOwl.java:292)
	at com.b2international.snowowl.core.SnowOwl.run(SnowOwl.java:267)
	at com.b2international.snowowl.core.SnowOwl.run(SnowOwl.java:255)
	at com.b2international.snowowl.server.product.SnowOwlServerActivator.start(SnowOwlServerActivator.java:51)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:598)
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.util.concurrent.ExecutionException: ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [GET], host [https://vpc-es-some-path.eu-west-1.es.amazonaws.com], URI [/_settings?master_timeout=30s&ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=true], status line [HTTP/1.1 401 Unauthorized]
{"Message":"Your request: '/_settings' is not allowed."}]; nested: ResponseException[method [GET], host [https://vpc-es-some-path.eu-west-1.es.amazonaws.com], URI [/_settings?master_timeout=30s&ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=true], status line [HTTP/1.1 401 Unauthorized]
{"Message":"Your request: '/_settings' is not allowed."}];
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.b2international.index.es.EsDocumentWriter.commit(EsDocumentWriter.java:150)
	... 28 common frames omitted
Caused by: org.elasticsearch.ElasticsearchStatusException: Unable to parse response body
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2033)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1777)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696)
	at org.elasticsearch.client.IndicesClient.getSettings(IndicesClient.java:858)
	at com.b2international.index.es.client.http.IndicesHttpClient.settings(IndicesHttpClient.java:116)
	at com.b2international.index.es.client.EsClientBase.checkClusterSettings(EsClientBase.java:145)
	at com.b2international.index.es.client.EsClientBase$ExpiringMemoizingSupplier.get(EsClientBase.java:207)
	at com.b2international.index.es.client.EsClientBase$ExpiringMemoizingSupplier.lambda$1(EsClientBase.java:224)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:47)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
	at com.b2international.index.es.client.EsClientBase.waitFor(EsClientBase.java:173)
	at com.b2international.index.es.client.EsClientBase$ExpiringMemoizingSupplier.waitUntilValue(EsClientBase.java:221)
	at com.b2international.index.es.client.EsClientBase.isIndexReadOnly(EsClientBase.java:156)
	at com.b2international.index.es.client.EsClientBase.status(EsClientBase.java:84)
	at com.b2international.index.es.client.EsClientBase.checkHealthy(EsClientBase.java:104)
	at com.b2international.index.es.client.http.EsHttpClient.updateByQuery(EsHttpClient.java:159)
	at com.b2international.index.es.admin.EsIndexAdmin.bulkIndexByScroll(EsIndexAdmin.java:556)
	at com.b2international.index.es.admin.EsIndexAdmin.bulkUpdate(EsIndexAdmin.java:531)
	at com.b2international.index.es.EsDocumentWriter.lambda$1(EsDocumentWriter.java:143)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:56)
	at com.b2international.index.es.EsDocumentWriter.commit(EsDocumentWriter.java:143)
	... 28 common frames omitted
	Suppressed: org.elasticsearch.common.ParsingException: Failed to parse object: expecting field with name [error] but found [Message]
		at org.elasticsearch.common.xcontent.XContentParserUtils.ensureFieldName(XContentParserUtils.java:50)
		at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:605)
		at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169)
		at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2053)
		at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2030)
		... 58 common frames omitted
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [https://vpc-es-some-path.eu-west-1.es.amazonaws.com], URI [/_settings?master_timeout=30s&ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=true], status line [HTTP/1.1 401 Unauthorized]
{"Message":"Your request: '/_settings' is not allowed."}

```

Could it be that Snow-owl hits a restricted api? 
I am wondering if using `/_all/_settings` (instead of /_settings) could be a possible alternative?

**Comment by apeteri** [comment]
Hi Martin,

Indeed, including the `/_all` prefix should work. `/_settings` on its own is not present on the allowed operations list for Amazon's Elasticsearch Service: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-es-operations.html#es_version_6_8

I added this change just now, it should be available in the next push to Docker Hub.

Regards,
András

**Comment by martinmart92** [comment]
great! thanks András! when would it be available?

**Comment by apeteri** [comment]
In about half an hour.

**Comment by apeteri** [comment]
b2ihealthcare/snow-owl-oss:7.x was updated to [ab0bf70cddaa8](https://hub.docker.com/layers/b2ihealthcare/snow-owl-oss/7.x/images/sha256-ab0bf70cddaa8917211bbe0dce0dda833a57234ff2a8bc6ac9f839a472844402).

**Comment by martinmart92** [comment]
thanks! 
good news, it worked! 
Snowowl was able to start and connect successfully to AWS ES.
Closing ticket.
