### ISSUE TITLE
"Broken" GET /fhir/ConceptMap endpoint, causing app to become completely unusable/die

### ISSUE THREAD

**Issue by ivelina-yordanova** [b2ihealthcare/snow-owl#463]
Hi,

The `GET /fhir/ConceptMap` endpoint always times-out and ends up returning 504 after approximately 59.20something - 59.30something seconds of waiting.

So, after noticing this I cancelled a request and this led to around 16 exceptions  like the one below right off the bat. 

```
com.b2international.snowowl.core.rest.ControllerExceptionMapper  Exception during request processing org.springframework.web.context.request.async.AsyncRequestTimeoutException: null
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:427)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:150)
	at org.eclipse.jetty.server.HttpChannelState$2.run(HttpChannelState.java:610)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1436)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1135)
	at org.eclipse.jetty.server.HttpChannelState.onTimeout(HttpChannelState.java:631)
	at org.eclipse.jetty.server.AsyncContextEvent.lambda$run$0(AsyncContextEvent.java:164)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It's also not just these 16 exceptions but they continue to be thrown on each other request and the other requests start returning 504 as well.

This continues basically until the application dies, or essentially it becomes unresponsive, the kube readiness probe fails and it appears as not running but there is no other exception besides the above.

Regards

**Comment by cmark** [comment]
This has been fixed in commits https://github.com/b2ihealthcare/snow-owl/commit/0ed6b1c31d218b841514c613fee4fa4f410ce8c8 and https://github.com/b2ihealthcare/snow-owl/commit/67d1e03fdb504db1a803e198ec5a77d040328934.
