### ISSUE TITLE
Import Snomed International issue

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#466]
Trying an import from an empty server, I got this in server side:

```
[2020-01-16T17:32:32.185] ERROR eventbus-64                                      c.b.snowowl.snomed.core.rest.services.SnomedRf2ImportService     Error during the import of: 825351e7-efdd-4e5d-a4ba-121f705616cc com.b2international.snowowl.core.api.SnowowlRuntimeException: com.b2international.snowowl.core.api.SnowowlRuntimeException: Couldn't execute query: listener timeout after waiting for [30000] ms
	at com.b2international.snowowl.snomed.datastore.request.rf2.SnomedRf2ImportRequest.execute(SnomedRf2ImportRequest.java:126)
	at com.b2international.snowowl.snomed.datastore.request.rf2.SnomedRf2ImportRequest.execute(SnomedRf2ImportRequest.java:1)
	at com.b2international.snowowl.core.events.DelegatingRequest.next(DelegatingRequest.java:72)
	at com.b2international.snowowl.datastore.request.RevisionIndexReadRequest.execute(RevisionIndexReadRequest.java:72)
	at com.b2international.snowowl.datastore.request.RevisionIndexReadRequest.execute(RevisionIndexReadRequest.java:1)
	at com.b2international.snowowl.core.events.DelegatingRequest.next(DelegatingRequest.java:72)
	at com.b2international.snowowl.datastore.request.BranchRequest.execute(BranchRequest.java:52)
	at com.b2international.snowowl.datastore.request.BranchRequest.execute(BranchRequest.java:1)
	at com.b2international.snowowl.core.events.DelegatingRequest.next(DelegatingRequest.java:72)
	at com.b2international.snowowl.datastore.request.IndexReadRequest.lambda$0(IndexReadRequest.java:45)
	at com.b2international.index.DefaultIndex.read(DefaultIndex.java:36)
	at com.b2international.snowowl.datastore.request.IndexReadRequest.execute(IndexReadRequest.java:43)
	at com.b2international.snowowl.datastore.request.IndexReadRequest.execute(IndexReadRequest.java:1)
	at com.b2international.snowowl.core.events.DelegatingRequest.next(DelegatingRequest.java:72)
	at com.b2international.snowowl.datastore.request.RepositoryRequest.execute(RepositoryRequest.java:62)
	at com.b2international.snowowl.core.events.DelegatingRequest.next(DelegatingRequest.java:72)
	at com.b2international.snowowl.core.rate.RateLimitingRequest.execute(RateLimitingRequest.java:50)
	at com.b2international.snowowl.core.events.DelegatingRequest.next(DelegatingRequest.java:72)
	at com.b2international.snowowl.core.authorization.AuthorizedRequest.execute(AuthorizedRequest.java:114)
	at com.b2international.snowowl.core.events.DelegatingRequest.next(DelegatingRequest.java:72)
	at com.b2international.snowowl.core.monitoring.MonitoredRequest.execute(MonitoredRequest.java:47)
	at com.b2international.snowowl.core.repository.ApiRequestHandler.handle(ApiRequestHandler.java:67)
	at com.b2international.snowowl.core.repository.ApiRequestHandler.handle(ApiRequestHandler.java:1)
	at com.b2international.snowowl.internal.eventbus.EventBus$1.run(EventBus.java:163)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.b2international.snowowl.core.api.SnowowlRuntimeException: Couldn't execute query: listener timeout after waiting for [30000] ms
	at com.b2international.snowowl.core.repository.RepositoryTransactionContext.commit(RepositoryTransactionContext.java:250)
	at com.b2international.snowowl.snomed.datastore.request.rf2.importer.Rf2TransactionContext.commit(Rf2TransactionContext.java:121)
	at com.b2international.snowowl.snomed.datastore.request.rf2.importer.Rf2EffectiveTimeSlice.doImport(Rf2EffectiveTimeSlice.java:233)
	at com.b2international.snowowl.snomed.datastore.request.rf2.SnomedRf2ImportRequest.doImport(SnomedRf2ImportRequest.java:164)
	at com.b2international.snowowl.snomed.datastore.request.rf2.SnomedRf2ImportRequest.execute(SnomedRf2ImportRequest.java:121)
	... 28 common frames omitted
Caused by: com.b2international.index.IndexException: Couldn't execute query: listener timeout after waiting for [30000] ms
	at com.b2international.index.es.EsDocumentSearcher.search(EsDocumentSearcher.java:190)
	at com.b2international.index.revision.DefaultRevisionSearcher.search(DefaultRevisionSearcher.java:107)
	at com.b2international.snowowl.snomed.datastore.index.change.ConceptChangeProcessor.process(ConceptChangeProcessor.java:156)
	at com.b2international.snowowl.datastore.index.BaseRepositoryPreCommitHook.doProcess(BaseRepositoryPreCommitHook.java:100)
	at com.b2international.snowowl.datastore.index.BaseRepositoryPreCommitHook.updateDocuments(BaseRepositoryPreCommitHook.java:92)
	at com.b2international.snowowl.datastore.index.BaseRepositoryPreCommitHook.lambda$0(BaseRepositoryPreCommitHook.java:46)
	at com.b2international.index.revision.DefaultRevisionIndex.lambda$0(DefaultRevisionIndex.java:112)
	at com.b2international.index.DefaultIndex.read(DefaultIndex.java:36)
	at com.b2international.index.revision.DefaultRevisionIndex.read(DefaultRevisionIndex.java:112)
	at com.b2international.index.revision.DefaultRevisionIndex.read(DefaultRevisionIndex.java:106)
	at com.b2international.index.revision.StagingArea.read(StagingArea.java:125)
	at com.b2international.snowowl.datastore.index.BaseRepositoryPreCommitHook.run(BaseRepositoryPreCommitHook.java:45)
	at com.b2international.index.revision.StagingArea.lambda$12(StagingArea.java:206)
```

Sorry for poor formatting, the important part is: `listener timeout after waiting for [30000] ms` probably returned by Elasticsearch. I did a quick dive in the code + googling..and found socket time configuration in ES client could be in cause.

I will retry increasing the socket timeout in SnowOwl ES client configuration to 60s instead of 30s, but I read some comments online that it is better to change the cient code and send smaller chunks. I am using an Elasticsearch serviced by AWS.

The file I am importing is `SnomedCT_InternationalRF2_PRODUCTION_20190131T120000Z.zip`

**Comment by cmark** [comment]
Hi @martinmart92,

Thank you for reporting the issue.
As you have described it configuring the `socketTimeout` might fix the issue and is considered a workaround.
The exception is actually coming from a query and not from the commit. Additional debug output would be helpful here, since the AWS ES Service has its own peculiarities and we do not have much experience with it.
Also, it would be great to expose the ES config `max_result_window` to our YML config file and let users configure it. That would be helpful in situations like this.

Cheers,
Mark

**Comment by cmark** [comment]
FYI: the `maxResultWindow` now can be configured in the latest Snow Owl 7.x and should always match the connected Elasticsearch's `max_result_window` setting, otherwise Elasticsearch might refuse to evaluate search requests with larger than its configured `max_result_window`.

**Comment by cmark** [comment]
Closing due to inactivity.
