### ISSUE TITLE
Support JDK 14+ compile time

### ISSUE THREAD

**Issue by cmark** [b2ihealthcare/snow-owl#481]
When trying to compile and use Snow Owl with `OpenJDK 13/AdoptJDK 13` it throws the following exception during REST API initialization:
```
ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [C:\dev\snow-owl-7x\git\snow-owl\core\com.b2international.snowowl.core.rest\target\classes\com\b2international\snowowl\core\rest\AbstractRestService.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 57
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:57)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:430)
	... 97 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 57
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:184)
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:166)
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:152)
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:273)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:54)
	... 100 common frames omitted
```

To fix the issue, Spring needs to be upgraded to `5.2.x`, see here:
https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions

**Comment by apeteri** [comment]
Would restricting the Java "release" compiler option for these projects help? https://www.baeldung.com/java-lang-unsupportedclassversion#2-changing-the-compiler-level

**Comment by cmark** [comment]
Yes, thank you, using the latest OpenJDK 13 actually works at runtime and fails with the above exception if compiling sources with compliance level Java 13.

**Comment by cmark** [comment]
Now that Oracle officially released JDK14 it would be great to have both runtime and compile time support for that version.
Elasticsearch still did not officially announce support for JDK14, though:
https://www.elastic.co/support/matrix#matrix_jvm

**Comment by cmark** [comment]
As Java 17 is now available as GA, I'll close this ticket in favor of upgrading our Java dependency to 17 when the required platform dependencies make it possible.
