### ISSUE TITLE
Snow Owl doesn't start from source in Eclipse

### ISSUE THREAD

**Issue by bluemana** [b2ihealthcare/snow-owl#670]
Hi,

Are there any additional steps required to start Snow Owl from source in Eclipse, other than those listed in the README? Bundles don't seem to locate implementation classes with the current setup. These are the steps to reproduce the problem:

1. Do a fresh install of Eclipse - Eclipse IDE for Eclipse Committers, Version: 2020-09 (4.17.0), Build id: 20200910-1200
2. Clone the `snow-owl` repo in a new Eclipse workspace directory
3. Import the project in Eclipse
4. Install the required Eclipse plugins and setup Eclipse according to the README
5. Execute the `mvn clean package` command
6. Setup the target environment according to the steps specified in the README
7. The run configuration displays the warning "A product with this name cannot be found in any required bundle:"

<img width="1068" alt="Screenshot 2020-09-21 at 15 48 03" src="https://user-images.githubusercontent.com/5190462/93785860-7b8cc000-fc26-11ea-8ef1-a3453552653a.png">

8. Run the configuration to see the following exception in the console:

```
 !ENTRY org.eclipse.osgi 4 0 2020-09-21 15:50:14.534
 !MESSAGE Application error
 !STACK 1
 java.lang.RuntimeException: No application id has been found.
 	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:246)
 	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
 	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
 	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

9. Add the plugins `cis`, `commons`, `core`, `fhir`, `net4j`, `snomed`, `tests` to the target file 
10. Run the configuration to see the following exception in the console:

```
!SESSION 2020-09-21 15:58:56.830 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.8
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product com.b2international.snowowl.server.product.product
Command-line arguments:  -product com.b2international.snowowl.server.product.product -data /Users/giulio.meneghin/Documents/eclipse-workspace/../runtime-snow-owl-oss -dev file:/Users/giulio.meneghin/Documents/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/snow-owl-oss/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -console

!ENTRY com.b2international.snowowl.core 4 0 2020-09-21 15:58:58.857
!MESSAGE bundle com.b2international.snowowl.core:7.9.2 (366)[com.b2international.snowowl.core.console.SnowOwlCommandProvider(27)] : Could not load implementation object class com.b2international.snowowl.core.console.SnowOwlCommandProvider
!STACK 0
java.lang.ClassNotFoundException: com.b2international.snowowl.core.console.SnowOwlCommandProvider cannot be found by com.b2international.snowowl.core_7.9.2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:620)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.initDependencyManagers(AbstractComponentManager.java:999)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1026)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:935)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:900)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:216)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:213)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:530)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:494)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:685)
	at org.eclipse.equinox.console.command.adapter.Activator$CommandCustomizer.addingService(Activator.java:182)
	at org.eclipse.equinox.console.command.adapter.Activator$CommandCustomizer.addingService(Activator.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
	at org.eclipse.equinox.console.command.adapter.Activator.start(Activator.java:223)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1015)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:603)
	at org.eclipse.osgi.container.Module.start(Module.java:467)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:439)
	at org.eclipse.core.runtime.internal.adaptor.ConsoleManager.checkForConsoleBundle(ConsoleManager.java:65)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:351)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by cmark** [comment]
Hi @bluemana,

The setup looks okay, the only thing that could be missing are projects from your workspace.
Could you please confirm that all projects from the Git repository are imported and open in your workspace?

The application ID is defined in the `com.b2international.snowowl.server.product` module. Make sure that is part of the launch configuration on the Plug-ins tab when you have it imported into your workspace.

This step is not required and might cause issues.
> 9. Add the plugins cis, commons, core, fhir, net4j, snomed, tests to the target file

Plug-ins in your workspace that are selected in the launch configuration will be on the classpath and be part of the target platform during launch.

I did update my Eclipse installation to the latest one (altough I've been using the 2020-03 so far) and can confirm that the steps should work fine.

Regards,
Mark

**Comment by bluemana** [comment]
Hi @cmark,

Yes, what I was missing was importing the projects into my workspace, thank you!

**Comment by cmark** [comment]
Hi @bluemana,

Glad to hear that.
I'll close this issue, feel free to raise another one if you have any other questions.

Cheers,
Mark
